name = "3d-neighborhood-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "neighborhood-db"
database_id = "7b6b4fff-9203-4c1b-91c9-adac51db1e81"

# Local development settings
[env.local]
